name: test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - name: Git checkout
      uses: actions/checkout@v6

    - name: Set up python3 ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel setuptools-scm[toml]
        pip install ".[test,lint]"
        pip list

    - name: Test with pytest
      run: |
        pytest -sv

    - name: Lint with ruff
      run: |
        ruff check .
